package jm.cms.mapper;

import java.util.List;
import jm.cms.model.CMS_MBRSESS;
import jm.cms.model.CMS_MBRSESSExample;
import org.apache.ibatis.annotations.Param;

public interface CMS_MBRSESSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    long countByExample(CMS_MBRSESSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int deleteByExample(CMS_MBRSESSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insert(CMS_MBRSESS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insertSelective(CMS_MBRSESS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    List<CMS_MBRSESS> selectByExample(CMS_MBRSESSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExampleSelective(@Param("record") CMS_MBRSESS record, @Param("example") CMS_MBRSESSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExample(@Param("record") CMS_MBRSESS record, @Param("example") CMS_MBRSESSExample example);
}