package jm.cms.mapper;

import java.util.List;
import jm.cms.model.CMS_MBRLOG;
import jm.cms.model.CMS_MBRLOGExample;
import org.apache.ibatis.annotations.Param;

public interface CMS_MBRLOGMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    long countByExample(CMS_MBRLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int deleteByExample(CMS_MBRLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insert(CMS_MBRLOG record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insertSelective(CMS_MBRLOG record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    List<CMS_MBRLOG> selectByExample(CMS_MBRLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExampleSelective(@Param("record") CMS_MBRLOG record, @Param("example") CMS_MBRLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExample(@Param("record") CMS_MBRLOG record, @Param("example") CMS_MBRLOGExample example);
}