package jm.cms.mapper;

import java.util.List;
import jm.cms.model.CMS_COMNCODE;
import jm.cms.model.CMS_COMNCODEExample;
import org.apache.ibatis.annotations.Param;

public interface CMS_COMNCODEMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    long countByExample(CMS_COMNCODEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int deleteByExample(CMS_COMNCODEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insert(CMS_COMNCODE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insertSelective(CMS_COMNCODE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    List<CMS_COMNCODE> selectByExample(CMS_COMNCODEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExampleSelective(@Param("record") CMS_COMNCODE record, @Param("example") CMS_COMNCODEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExample(@Param("record") CMS_COMNCODE record, @Param("example") CMS_COMNCODEExample example);
}