package jm.cms.mapper;

import java.util.List;
import jm.cms.model.CMS_LOGINLOG;
import jm.cms.model.CMS_LOGINLOGExample;
import org.apache.ibatis.annotations.Param;

public interface CMS_LOGINLOGMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    long countByExample(CMS_LOGINLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int deleteByExample(CMS_LOGINLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insert(CMS_LOGINLOG record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insertSelective(CMS_LOGINLOG record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    List<CMS_LOGINLOG> selectByExample(CMS_LOGINLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExampleSelective(@Param("record") CMS_LOGINLOG record, @Param("example") CMS_LOGINLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExample(@Param("record") CMS_LOGINLOG record, @Param("example") CMS_LOGINLOGExample example);
}