package jm.cms.mapper;

import java.util.List;
import jm.cms.model.CMS_IPCONFIG;
import jm.cms.model.CMS_IPCONFIGExample;
import org.apache.ibatis.annotations.Param;

public interface CMS_IPCONFIGMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	long countByExample(CMS_IPCONFIGExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	int deleteByExample(CMS_IPCONFIGExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	int insert(CMS_IPCONFIG record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	int insertSelective(CMS_IPCONFIG record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	List<CMS_IPCONFIG> selectByExample(CMS_IPCONFIGExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	int updateByExampleSelective(@Param("record") CMS_IPCONFIG record, @Param("example") CMS_IPCONFIGExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	int updateByExample(@Param("record") CMS_IPCONFIG record, @Param("example") CMS_IPCONFIGExample example);
}