package jm.cms.mapper;

import java.util.List;
import jm.cms.model.CMS_VISITLOG;
import jm.cms.model.CMS_VISITLOGExample;
import org.apache.ibatis.annotations.Param;

public interface CMS_VISITLOGMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    long countByExample(CMS_VISITLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int deleteByExample(CMS_VISITLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insert(CMS_VISITLOG record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int insertSelective(CMS_VISITLOG record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    List<CMS_VISITLOG> selectByExample(CMS_VISITLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExampleSelective(@Param("record") CMS_VISITLOG record, @Param("example") CMS_VISITLOGExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    int updateByExample(@Param("record") CMS_VISITLOG record, @Param("example") CMS_VISITLOGExample example);
}