package jm.cms.mapper;

import java.util.List;
import jm.cms.model.IpConfig;
import jm.cms.model.IpConfigExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IpConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    long countByExample(IpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int deleteByExample(IpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insert(IpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insertSelective(IpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    List<IpConfig> selectByExample(IpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExampleSelective(@Param("record") IpConfig record, @Param("example") IpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExample(@Param("record") IpConfig record, @Param("example") IpConfigExample example);
}