package jm.cms.mapper;

import java.util.List;
import jm.cms.model.LoginLog;
import jm.cms.model.LoginLogExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    long countByExample(LoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int deleteByExample(LoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insert(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insertSelective(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    List<LoginLog> selectByExample(LoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExampleSelective(@Param("record") LoginLog record, @Param("example") LoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LOGINLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExample(@Param("record") LoginLog record, @Param("example") LoginLogExample example);
}