package jm.cms.mapper;

import java.util.List;
import jm.cms.model.MenuType;
import jm.cms.model.MenuTypeExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MenuTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    long countByExample(MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int deleteByExample(MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insert(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insertSelective(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    List<MenuType> selectByExample(MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExampleSelective(@Param("record") MenuType record, @Param("example") MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExample(@Param("record") MenuType record, @Param("example") MenuTypeExample example);
}