package jm.cms.mapper;

import java.util.List;
import jm.cms.model.VisitLog;
import jm.cms.model.VisitLogExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface VisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    long countByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int deleteByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insert(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int insertSelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    List<VisitLog> selectByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExampleSelective(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    int updateByExample(@Param("record") VisitLog record, @Param("example") VisitLogExample example);
}