package com.cms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MbrLogExample {
    /**
     
     * This field corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    protected String orderByClause;

    /**
     
     * This field corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    protected boolean distinct;

    /**
     
     * This field corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    protected List<Criteria> oredCriteria;

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public MbrLogExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMbrlogIdIsNull() {
            addCriterion("MBRLOG_ID is null");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdIsNotNull() {
            addCriterion("MBRLOG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdEqualTo(String value) {
            addCriterion("MBRLOG_ID =", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdNotEqualTo(String value) {
            addCriterion("MBRLOG_ID <>", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdGreaterThan(String value) {
            addCriterion("MBRLOG_ID >", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdGreaterThanOrEqualTo(String value) {
            addCriterion("MBRLOG_ID >=", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdLessThan(String value) {
            addCriterion("MBRLOG_ID <", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdLessThanOrEqualTo(String value) {
            addCriterion("MBRLOG_ID <=", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdLike(String value) {
            addCriterion("MBRLOG_ID like", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdNotLike(String value) {
            addCriterion("MBRLOG_ID not like", value, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdIn(List<String> values) {
            addCriterion("MBRLOG_ID in", values, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdNotIn(List<String> values) {
            addCriterion("MBRLOG_ID not in", values, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdBetween(String value1, String value2) {
            addCriterion("MBRLOG_ID between", value1, value2, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrlogIdNotBetween(String value1, String value2) {
            addCriterion("MBRLOG_ID not between", value1, value2, "mbrlogId");
            return (Criteria) this;
        }

        public Criteria andMbrIdIsNull() {
            addCriterion("MBR_ID is null");
            return (Criteria) this;
        }

        public Criteria andMbrIdIsNotNull() {
            addCriterion("MBR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMbrIdEqualTo(String value) {
            addCriterion("MBR_ID =", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotEqualTo(String value) {
            addCriterion("MBR_ID <>", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThan(String value) {
            addCriterion("MBR_ID >", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_ID >=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThan(String value) {
            addCriterion("MBR_ID <", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThanOrEqualTo(String value) {
            addCriterion("MBR_ID <=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLike(String value) {
            addCriterion("MBR_ID like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotLike(String value) {
            addCriterion("MBR_ID not like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdIn(List<String> values) {
            addCriterion("MBR_ID in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotIn(List<String> values) {
            addCriterion("MBR_ID not in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdBetween(String value1, String value2) {
            addCriterion("MBR_ID between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotBetween(String value1, String value2) {
            addCriterion("MBR_ID not between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentIsNull() {
            addCriterion("MBRLOG_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentIsNotNull() {
            addCriterion("MBRLOG_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentEqualTo(String value) {
            addCriterion("MBRLOG_CONTENT =", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentNotEqualTo(String value) {
            addCriterion("MBRLOG_CONTENT <>", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentGreaterThan(String value) {
            addCriterion("MBRLOG_CONTENT >", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentGreaterThanOrEqualTo(String value) {
            addCriterion("MBRLOG_CONTENT >=", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentLessThan(String value) {
            addCriterion("MBRLOG_CONTENT <", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentLessThanOrEqualTo(String value) {
            addCriterion("MBRLOG_CONTENT <=", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentLike(String value) {
            addCriterion("MBRLOG_CONTENT like", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentNotLike(String value) {
            addCriterion("MBRLOG_CONTENT not like", value, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentIn(List<String> values) {
            addCriterion("MBRLOG_CONTENT in", values, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentNotIn(List<String> values) {
            addCriterion("MBRLOG_CONTENT not in", values, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentBetween(String value1, String value2) {
            addCriterion("MBRLOG_CONTENT between", value1, value2, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogContentNotBetween(String value1, String value2) {
            addCriterion("MBRLOG_CONTENT not between", value1, value2, "mbrlogContent");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusIsNull() {
            addCriterion("MBRLOG_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusIsNotNull() {
            addCriterion("MBRLOG_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusEqualTo(Short value) {
            addCriterion("MBRLOG_STATUS =", value, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusNotEqualTo(Short value) {
            addCriterion("MBRLOG_STATUS <>", value, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusGreaterThan(Short value) {
            addCriterion("MBRLOG_STATUS >", value, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("MBRLOG_STATUS >=", value, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusLessThan(Short value) {
            addCriterion("MBRLOG_STATUS <", value, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusLessThanOrEqualTo(Short value) {
            addCriterion("MBRLOG_STATUS <=", value, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusIn(List<Short> values) {
            addCriterion("MBRLOG_STATUS in", values, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusNotIn(List<Short> values) {
            addCriterion("MBRLOG_STATUS not in", values, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusBetween(Short value1, Short value2) {
            addCriterion("MBRLOG_STATUS between", value1, value2, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andMbrlogStatusNotBetween(Short value1, Short value2) {
            addCriterion("MBRLOG_STATUS not between", value1, value2, "mbrlogStatus");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("CREATED =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("CREATED <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("CREATED >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("CREATED <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("CREATED <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("CREATED in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("CREATED not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("CREATED between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("CREATED not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andMbrNmIsNull() {
            addCriterion("MBR_NM is null");
            return (Criteria) this;
        }

        public Criteria andMbrNmIsNotNull() {
            addCriterion("MBR_NM is not null");
            return (Criteria) this;
        }

        public Criteria andMbrNmEqualTo(String value) {
            addCriterion("MBR_NM =", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotEqualTo(String value) {
            addCriterion("MBR_NM <>", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmGreaterThan(String value) {
            addCriterion("MBR_NM >", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_NM >=", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmLessThan(String value) {
            addCriterion("MBR_NM <", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmLessThanOrEqualTo(String value) {
            addCriterion("MBR_NM <=", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmLike(String value) {
            addCriterion("MBR_NM like", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotLike(String value) {
            addCriterion("MBR_NM not like", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmIn(List<String> values) {
            addCriterion("MBR_NM in", values, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotIn(List<String> values) {
            addCriterion("MBR_NM not in", values, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmBetween(String value1, String value2) {
            addCriterion("MBR_NM between", value1, value2, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotBetween(String value1, String value2) {
            addCriterion("MBR_NM not between", value1, value2, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrLoginIsNull() {
            addCriterion("MBR_LOGIN is null");
            return (Criteria) this;
        }

        public Criteria andMbrLoginIsNotNull() {
            addCriterion("MBR_LOGIN is not null");
            return (Criteria) this;
        }

        public Criteria andMbrLoginEqualTo(String value) {
            addCriterion("MBR_LOGIN =", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotEqualTo(String value) {
            addCriterion("MBR_LOGIN <>", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginGreaterThan(String value) {
            addCriterion("MBR_LOGIN >", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_LOGIN >=", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginLessThan(String value) {
            addCriterion("MBR_LOGIN <", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginLessThanOrEqualTo(String value) {
            addCriterion("MBR_LOGIN <=", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginLike(String value) {
            addCriterion("MBR_LOGIN like", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotLike(String value) {
            addCriterion("MBR_LOGIN not like", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginIn(List<String> values) {
            addCriterion("MBR_LOGIN in", values, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotIn(List<String> values) {
            addCriterion("MBR_LOGIN not in", values, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginBetween(String value1, String value2) {
            addCriterion("MBR_LOGIN between", value1, value2, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotBetween(String value1, String value2) {
            addCriterion("MBR_LOGIN not between", value1, value2, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrIpIsNull() {
            addCriterion("MBR_IP is null");
            return (Criteria) this;
        }

        public Criteria andMbrIpIsNotNull() {
            addCriterion("MBR_IP is not null");
            return (Criteria) this;
        }

        public Criteria andMbrIpEqualTo(String value) {
            addCriterion("MBR_IP =", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpNotEqualTo(String value) {
            addCriterion("MBR_IP <>", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpGreaterThan(String value) {
            addCriterion("MBR_IP >", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_IP >=", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpLessThan(String value) {
            addCriterion("MBR_IP <", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpLessThanOrEqualTo(String value) {
            addCriterion("MBR_IP <=", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpLike(String value) {
            addCriterion("MBR_IP like", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpNotLike(String value) {
            addCriterion("MBR_IP not like", value, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpIn(List<String> values) {
            addCriterion("MBR_IP in", values, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpNotIn(List<String> values) {
            addCriterion("MBR_IP not in", values, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpBetween(String value1, String value2) {
            addCriterion("MBR_IP between", value1, value2, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andMbrIpNotBetween(String value1, String value2) {
            addCriterion("MBR_IP not between", value1, value2, "mbrIp");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginIsNull() {
            addCriterion("ACT_MBR_LOGIN is null");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginIsNotNull() {
            addCriterion("ACT_MBR_LOGIN is not null");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginEqualTo(String value) {
            addCriterion("ACT_MBR_LOGIN =", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginNotEqualTo(String value) {
            addCriterion("ACT_MBR_LOGIN <>", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginGreaterThan(String value) {
            addCriterion("ACT_MBR_LOGIN >", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_MBR_LOGIN >=", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginLessThan(String value) {
            addCriterion("ACT_MBR_LOGIN <", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginLessThanOrEqualTo(String value) {
            addCriterion("ACT_MBR_LOGIN <=", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginLike(String value) {
            addCriterion("ACT_MBR_LOGIN like", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginNotLike(String value) {
            addCriterion("ACT_MBR_LOGIN not like", value, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginIn(List<String> values) {
            addCriterion("ACT_MBR_LOGIN in", values, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginNotIn(List<String> values) {
            addCriterion("ACT_MBR_LOGIN not in", values, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginBetween(String value1, String value2) {
            addCriterion("ACT_MBR_LOGIN between", value1, value2, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andActMbrLoginNotBetween(String value1, String value2) {
            addCriterion("ACT_MBR_LOGIN not between", value1, value2, "actMbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathIsNull() {
            addCriterion("MBRLOG_PATH is null");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathIsNotNull() {
            addCriterion("MBRLOG_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathEqualTo(String value) {
            addCriterion("MBRLOG_PATH =", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathNotEqualTo(String value) {
            addCriterion("MBRLOG_PATH <>", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathGreaterThan(String value) {
            addCriterion("MBRLOG_PATH >", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathGreaterThanOrEqualTo(String value) {
            addCriterion("MBRLOG_PATH >=", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathLessThan(String value) {
            addCriterion("MBRLOG_PATH <", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathLessThanOrEqualTo(String value) {
            addCriterion("MBRLOG_PATH <=", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathLike(String value) {
            addCriterion("MBRLOG_PATH like", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathNotLike(String value) {
            addCriterion("MBRLOG_PATH not like", value, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathIn(List<String> values) {
            addCriterion("MBRLOG_PATH in", values, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathNotIn(List<String> values) {
            addCriterion("MBRLOG_PATH not in", values, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathBetween(String value1, String value2) {
            addCriterion("MBRLOG_PATH between", value1, value2, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogPathNotBetween(String value1, String value2) {
            addCriterion("MBRLOG_PATH not between", value1, value2, "mbrlogPath");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01IsNull() {
            addCriterion("MBRLOG_EXT01 is null");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01IsNotNull() {
            addCriterion("MBRLOG_EXT01 is not null");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01EqualTo(String value) {
            addCriterion("MBRLOG_EXT01 =", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01NotEqualTo(String value) {
            addCriterion("MBRLOG_EXT01 <>", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01GreaterThan(String value) {
            addCriterion("MBRLOG_EXT01 >", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01GreaterThanOrEqualTo(String value) {
            addCriterion("MBRLOG_EXT01 >=", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01LessThan(String value) {
            addCriterion("MBRLOG_EXT01 <", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01LessThanOrEqualTo(String value) {
            addCriterion("MBRLOG_EXT01 <=", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01Like(String value) {
            addCriterion("MBRLOG_EXT01 like", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01NotLike(String value) {
            addCriterion("MBRLOG_EXT01 not like", value, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01In(List<String> values) {
            addCriterion("MBRLOG_EXT01 in", values, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01NotIn(List<String> values) {
            addCriterion("MBRLOG_EXT01 not in", values, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01Between(String value1, String value2) {
            addCriterion("MBRLOG_EXT01 between", value1, value2, "mbrlogExt01");
            return (Criteria) this;
        }

        public Criteria andMbrlogExt01NotBetween(String value1, String value2) {
            addCriterion("MBRLOG_EXT01 not between", value1, value2, "mbrlogExt01");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 06 19:23:16 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBRLOG
     *
     
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}