package com.cms.model;

import java.util.ArrayList;
import java.util.List;

public class MenuTypeExample {
    /**
     
     * This field corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    protected String orderByClause;

    /**
     
     * This field corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    protected boolean distinct;

    /**
     
     * This field corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    protected List<Criteria> oredCriteria;

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public MenuTypeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     
     * This method corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("MENU_ID is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("MENU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(String value) {
            addCriterion("MENU_ID =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(String value) {
            addCriterion("MENU_ID <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(String value) {
            addCriterion("MENU_ID >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_ID >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(String value) {
            addCriterion("MENU_ID <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(String value) {
            addCriterion("MENU_ID <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLike(String value) {
            addCriterion("MENU_ID like", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotLike(String value) {
            addCriterion("MENU_ID not like", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<String> values) {
            addCriterion("MENU_ID in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<String> values) {
            addCriterion("MENU_ID not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(String value1, String value2) {
            addCriterion("MENU_ID between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(String value1, String value2) {
            addCriterion("MENU_ID not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(String value) {
            addCriterion("TYPE_ID =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(String value) {
            addCriterion("TYPE_ID <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(String value) {
            addCriterion("TYPE_ID >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_ID >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(String value) {
            addCriterion("TYPE_ID <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(String value) {
            addCriterion("TYPE_ID <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLike(String value) {
            addCriterion("TYPE_ID like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotLike(String value) {
            addCriterion("TYPE_ID not like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<String> values) {
            addCriterion("TYPE_ID in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<String> values) {
            addCriterion("TYPE_ID not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(String value1, String value2) {
            addCriterion("TYPE_ID between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(String value1, String value2) {
            addCriterion("TYPE_ID not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andIslistIsNull() {
            addCriterion("ISLIST is null");
            return (Criteria) this;
        }

        public Criteria andIslistIsNotNull() {
            addCriterion("ISLIST is not null");
            return (Criteria) this;
        }

        public Criteria andIslistEqualTo(String value) {
            addCriterion("ISLIST =", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistNotEqualTo(String value) {
            addCriterion("ISLIST <>", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistGreaterThan(String value) {
            addCriterion("ISLIST >", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistGreaterThanOrEqualTo(String value) {
            addCriterion("ISLIST >=", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistLessThan(String value) {
            addCriterion("ISLIST <", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistLessThanOrEqualTo(String value) {
            addCriterion("ISLIST <=", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistLike(String value) {
            addCriterion("ISLIST like", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistNotLike(String value) {
            addCriterion("ISLIST not like", value, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistIn(List<String> values) {
            addCriterion("ISLIST in", values, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistNotIn(List<String> values) {
            addCriterion("ISLIST not in", values, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistBetween(String value1, String value2) {
            addCriterion("ISLIST between", value1, value2, "islist");
            return (Criteria) this;
        }

        public Criteria andIslistNotBetween(String value1, String value2) {
            addCriterion("ISLIST not between", value1, value2, "islist");
            return (Criteria) this;
        }

        public Criteria andIsviewIsNull() {
            addCriterion("ISVIEW is null");
            return (Criteria) this;
        }

        public Criteria andIsviewIsNotNull() {
            addCriterion("ISVIEW is not null");
            return (Criteria) this;
        }

        public Criteria andIsviewEqualTo(String value) {
            addCriterion("ISVIEW =", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewNotEqualTo(String value) {
            addCriterion("ISVIEW <>", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewGreaterThan(String value) {
            addCriterion("ISVIEW >", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewGreaterThanOrEqualTo(String value) {
            addCriterion("ISVIEW >=", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewLessThan(String value) {
            addCriterion("ISVIEW <", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewLessThanOrEqualTo(String value) {
            addCriterion("ISVIEW <=", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewLike(String value) {
            addCriterion("ISVIEW like", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewNotLike(String value) {
            addCriterion("ISVIEW not like", value, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewIn(List<String> values) {
            addCriterion("ISVIEW in", values, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewNotIn(List<String> values) {
            addCriterion("ISVIEW not in", values, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewBetween(String value1, String value2) {
            addCriterion("ISVIEW between", value1, value2, "isview");
            return (Criteria) this;
        }

        public Criteria andIsviewNotBetween(String value1, String value2) {
            addCriterion("ISVIEW not between", value1, value2, "isview");
            return (Criteria) this;
        }

        public Criteria andIswriteIsNull() {
            addCriterion("ISWRITE is null");
            return (Criteria) this;
        }

        public Criteria andIswriteIsNotNull() {
            addCriterion("ISWRITE is not null");
            return (Criteria) this;
        }

        public Criteria andIswriteEqualTo(String value) {
            addCriterion("ISWRITE =", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteNotEqualTo(String value) {
            addCriterion("ISWRITE <>", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteGreaterThan(String value) {
            addCriterion("ISWRITE >", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteGreaterThanOrEqualTo(String value) {
            addCriterion("ISWRITE >=", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteLessThan(String value) {
            addCriterion("ISWRITE <", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteLessThanOrEqualTo(String value) {
            addCriterion("ISWRITE <=", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteLike(String value) {
            addCriterion("ISWRITE like", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteNotLike(String value) {
            addCriterion("ISWRITE not like", value, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteIn(List<String> values) {
            addCriterion("ISWRITE in", values, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteNotIn(List<String> values) {
            addCriterion("ISWRITE not in", values, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteBetween(String value1, String value2) {
            addCriterion("ISWRITE between", value1, value2, "iswrite");
            return (Criteria) this;
        }

        public Criteria andIswriteNotBetween(String value1, String value2) {
            addCriterion("ISWRITE not between", value1, value2, "iswrite");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdIsNull() {
            addCriterion("MAPNG_CREAT_ID is null");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdIsNotNull() {
            addCriterion("MAPNG_CREAT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdEqualTo(String value) {
            addCriterion("MAPNG_CREAT_ID =", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdNotEqualTo(String value) {
            addCriterion("MAPNG_CREAT_ID <>", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdGreaterThan(String value) {
            addCriterion("MAPNG_CREAT_ID >", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdGreaterThanOrEqualTo(String value) {
            addCriterion("MAPNG_CREAT_ID >=", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdLessThan(String value) {
            addCriterion("MAPNG_CREAT_ID <", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdLessThanOrEqualTo(String value) {
            addCriterion("MAPNG_CREAT_ID <=", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdLike(String value) {
            addCriterion("MAPNG_CREAT_ID like", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdNotLike(String value) {
            addCriterion("MAPNG_CREAT_ID not like", value, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdIn(List<String> values) {
            addCriterion("MAPNG_CREAT_ID in", values, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdNotIn(List<String> values) {
            addCriterion("MAPNG_CREAT_ID not in", values, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdBetween(String value1, String value2) {
            addCriterion("MAPNG_CREAT_ID between", value1, value2, "mapngCreatId");
            return (Criteria) this;
        }

        public Criteria andMapngCreatIdNotBetween(String value1, String value2) {
            addCriterion("MAPNG_CREAT_ID not between", value1, value2, "mapngCreatId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSADMENUTYPE
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 06 19:23:16 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSADMENUTYPE
     *
     
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}