server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    basedir: .

spring:
  profiles.active: local
  application.name: gradle_boot
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .html
#      suffix: .jsp 

mybatis:
  config-location: classpath:sqlmap/mybatis-config.xml
  mapper-locations: classpath:sqlmap/mapper/*.xml
  type-aliases-package: com.user.model  # mybatis 매핑 type을 짧게 쓰기 위한 설정

#server.tomcat.basedir: .
#server.tomcat.accesslog:
#  enabled: false
#  pattern: "%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{X-Forwarded-For}i\t%b"
#  directory: logs/
#  prefix: access-log
#  suffix: .log
logging:
  config: classpath:logback-spring.xml
  level:     com.user.mapper: trace # mapper 이하를 로깅 위치로 설정.
    com.user.service: trace

---

spring:
  profiles: local
  datasource:
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:log4jdbc:mysql://15.164.129.107:3306/connector
    url: jdbc:mysql://15.164.129.107:3306/connector
    username: user
    password: user
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 3600000

---

spring:
  profiles: dev
  datasource:
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/
    username: user
    password: user
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 3600000


#globals:
#  file.upload-path: /sysoft/upload/consulting/
#  safe.download-path: /home/sysoft/v01-api/tomcat-8.5.12/webapps/v01-api/WEB-INF/classes/static/down/
#  sch.ip-address: 115.68.106.113
#  cust-prtc-amt-url: http://115.68.106.113:9090/bid-manager/etcunusl/CustPrtcAmtCustNotiSch/
#  auto-anals-ach-url: http://115.68.106.113:9090/bid-manager/etcunusl/AutoAnalsAch/
