package jm.cms.model;

import java.util.Date;

public class CMS_IPCONFIG {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.CMS_TYPE
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private String cmsType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.IP_ADDR
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private String ipAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.IP_BAND
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private String ipBand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.IP_DESC
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private String ipDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.MBR_ID
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private String mbrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.CREATED
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.MODIFIED
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private Date modified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CMSIPCONFIGINFO.ISDEL
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	private Short isdel;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public CMS_IPCONFIG(String cmsType, String ipAddr, String ipBand, String ipDesc, String mbrId, Date created,
			Date modified, Short isdel) {
		this.cmsType = cmsType;
		this.ipAddr = ipAddr;
		this.ipBand = ipBand;
		this.ipDesc = ipDesc;
		this.mbrId = mbrId;
		this.created = created;
		this.modified = modified;
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CMSIPCONFIGINFO
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public CMS_IPCONFIG() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.CMS_TYPE
	 * @return  the value of TB_CMSIPCONFIGINFO.CMS_TYPE
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public String getCmsType() {
		return cmsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.CMS_TYPE
	 * @param cmsType  the value for TB_CMSIPCONFIGINFO.CMS_TYPE
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setCmsType(String cmsType) {
		this.cmsType = cmsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.IP_ADDR
	 * @return  the value of TB_CMSIPCONFIGINFO.IP_ADDR
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public String getIpAddr() {
		return ipAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.IP_ADDR
	 * @param ipAddr  the value for TB_CMSIPCONFIGINFO.IP_ADDR
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.IP_BAND
	 * @return  the value of TB_CMSIPCONFIGINFO.IP_BAND
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public String getIpBand() {
		return ipBand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.IP_BAND
	 * @param ipBand  the value for TB_CMSIPCONFIGINFO.IP_BAND
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setIpBand(String ipBand) {
		this.ipBand = ipBand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.IP_DESC
	 * @return  the value of TB_CMSIPCONFIGINFO.IP_DESC
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public String getIpDesc() {
		return ipDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.IP_DESC
	 * @param ipDesc  the value for TB_CMSIPCONFIGINFO.IP_DESC
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setIpDesc(String ipDesc) {
		this.ipDesc = ipDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.MBR_ID
	 * @return  the value of TB_CMSIPCONFIGINFO.MBR_ID
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public String getMbrId() {
		return mbrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.MBR_ID
	 * @param mbrId  the value for TB_CMSIPCONFIGINFO.MBR_ID
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setMbrId(String mbrId) {
		this.mbrId = mbrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.CREATED
	 * @return  the value of TB_CMSIPCONFIGINFO.CREATED
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.CREATED
	 * @param created  the value for TB_CMSIPCONFIGINFO.CREATED
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.MODIFIED
	 * @return  the value of TB_CMSIPCONFIGINFO.MODIFIED
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public Date getModified() {
		return modified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.MODIFIED
	 * @param modified  the value for TB_CMSIPCONFIGINFO.MODIFIED
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setModified(Date modified) {
		this.modified = modified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CMSIPCONFIGINFO.ISDEL
	 * @return  the value of TB_CMSIPCONFIGINFO.ISDEL
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public Short getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CMSIPCONFIGINFO.ISDEL
	 * @param isdel  the value for TB_CMSIPCONFIGINFO.ISDEL
	 * @mbg.generated  Fri Jun 05 23:25:09 KST 2020
	 */
	public void setIsdel(Short isdel) {
		this.isdel = isdel;
	}
}