package jm.cms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CMS_MBRExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public CMS_MBRExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMbrIdIsNull() {
            addCriterion("MBR_ID is null");
            return (Criteria) this;
        }

        public Criteria andMbrIdIsNotNull() {
            addCriterion("MBR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMbrIdEqualTo(String value) {
            addCriterion("MBR_ID =", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotEqualTo(String value) {
            addCriterion("MBR_ID <>", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThan(String value) {
            addCriterion("MBR_ID >", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_ID >=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThan(String value) {
            addCriterion("MBR_ID <", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThanOrEqualTo(String value) {
            addCriterion("MBR_ID <=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLike(String value) {
            addCriterion("MBR_ID like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotLike(String value) {
            addCriterion("MBR_ID not like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdIn(List<String> values) {
            addCriterion("MBR_ID in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotIn(List<String> values) {
            addCriterion("MBR_ID not in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdBetween(String value1, String value2) {
            addCriterion("MBR_ID between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotBetween(String value1, String value2) {
            addCriterion("MBR_ID not between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrLoginIsNull() {
            addCriterion("MBR_LOGIN is null");
            return (Criteria) this;
        }

        public Criteria andMbrLoginIsNotNull() {
            addCriterion("MBR_LOGIN is not null");
            return (Criteria) this;
        }

        public Criteria andMbrLoginEqualTo(String value) {
            addCriterion("MBR_LOGIN =", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotEqualTo(String value) {
            addCriterion("MBR_LOGIN <>", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginGreaterThan(String value) {
            addCriterion("MBR_LOGIN >", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_LOGIN >=", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginLessThan(String value) {
            addCriterion("MBR_LOGIN <", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginLessThanOrEqualTo(String value) {
            addCriterion("MBR_LOGIN <=", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginLike(String value) {
            addCriterion("MBR_LOGIN like", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotLike(String value) {
            addCriterion("MBR_LOGIN not like", value, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginIn(List<String> values) {
            addCriterion("MBR_LOGIN in", values, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotIn(List<String> values) {
            addCriterion("MBR_LOGIN not in", values, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginBetween(String value1, String value2) {
            addCriterion("MBR_LOGIN between", value1, value2, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrLoginNotBetween(String value1, String value2) {
            addCriterion("MBR_LOGIN not between", value1, value2, "mbrLogin");
            return (Criteria) this;
        }

        public Criteria andMbrNmIsNull() {
            addCriterion("MBR_NM is null");
            return (Criteria) this;
        }

        public Criteria andMbrNmIsNotNull() {
            addCriterion("MBR_NM is not null");
            return (Criteria) this;
        }

        public Criteria andMbrNmEqualTo(String value) {
            addCriterion("MBR_NM =", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotEqualTo(String value) {
            addCriterion("MBR_NM <>", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmGreaterThan(String value) {
            addCriterion("MBR_NM >", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_NM >=", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmLessThan(String value) {
            addCriterion("MBR_NM <", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmLessThanOrEqualTo(String value) {
            addCriterion("MBR_NM <=", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmLike(String value) {
            addCriterion("MBR_NM like", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotLike(String value) {
            addCriterion("MBR_NM not like", value, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmIn(List<String> values) {
            addCriterion("MBR_NM in", values, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotIn(List<String> values) {
            addCriterion("MBR_NM not in", values, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmBetween(String value1, String value2) {
            addCriterion("MBR_NM between", value1, value2, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andMbrNmNotBetween(String value1, String value2) {
            addCriterion("MBR_NM not between", value1, value2, "mbrNm");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("PASSWD is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("PASSWD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("PASSWD =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("PASSWD <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("PASSWD >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWD >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("PASSWD <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("PASSWD <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("PASSWD like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("PASSWD not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("PASSWD in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("PASSWD not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("PASSWD between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("PASSWD not between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(String value) {
            addCriterion("TYPE_ID =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(String value) {
            addCriterion("TYPE_ID <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(String value) {
            addCriterion("TYPE_ID >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_ID >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(String value) {
            addCriterion("TYPE_ID <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(String value) {
            addCriterion("TYPE_ID <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLike(String value) {
            addCriterion("TYPE_ID like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotLike(String value) {
            addCriterion("TYPE_ID not like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<String> values) {
            addCriterion("TYPE_ID in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<String> values) {
            addCriterion("TYPE_ID not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(String value1, String value2) {
            addCriterion("TYPE_ID between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(String value1, String value2) {
            addCriterion("TYPE_ID not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andPosNmIsNull() {
            addCriterion("POS_NM is null");
            return (Criteria) this;
        }

        public Criteria andPosNmIsNotNull() {
            addCriterion("POS_NM is not null");
            return (Criteria) this;
        }

        public Criteria andPosNmEqualTo(String value) {
            addCriterion("POS_NM =", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmNotEqualTo(String value) {
            addCriterion("POS_NM <>", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmGreaterThan(String value) {
            addCriterion("POS_NM >", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmGreaterThanOrEqualTo(String value) {
            addCriterion("POS_NM >=", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmLessThan(String value) {
            addCriterion("POS_NM <", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmLessThanOrEqualTo(String value) {
            addCriterion("POS_NM <=", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmLike(String value) {
            addCriterion("POS_NM like", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmNotLike(String value) {
            addCriterion("POS_NM not like", value, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmIn(List<String> values) {
            addCriterion("POS_NM in", values, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmNotIn(List<String> values) {
            addCriterion("POS_NM not in", values, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmBetween(String value1, String value2) {
            addCriterion("POS_NM between", value1, value2, "posNm");
            return (Criteria) this;
        }

        public Criteria andPosNmNotBetween(String value1, String value2) {
            addCriterion("POS_NM not between", value1, value2, "posNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmIsNull() {
            addCriterion("ORG_NM is null");
            return (Criteria) this;
        }

        public Criteria andOrgNmIsNotNull() {
            addCriterion("ORG_NM is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNmEqualTo(String value) {
            addCriterion("ORG_NM =", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmNotEqualTo(String value) {
            addCriterion("ORG_NM <>", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmGreaterThan(String value) {
            addCriterion("ORG_NM >", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NM >=", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmLessThan(String value) {
            addCriterion("ORG_NM <", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmLessThanOrEqualTo(String value) {
            addCriterion("ORG_NM <=", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmLike(String value) {
            addCriterion("ORG_NM like", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmNotLike(String value) {
            addCriterion("ORG_NM not like", value, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmIn(List<String> values) {
            addCriterion("ORG_NM in", values, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmNotIn(List<String> values) {
            addCriterion("ORG_NM not in", values, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmBetween(String value1, String value2) {
            addCriterion("ORG_NM between", value1, value2, "orgNm");
            return (Criteria) this;
        }

        public Criteria andOrgNmNotBetween(String value1, String value2) {
            addCriterion("ORG_NM not between", value1, value2, "orgNm");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("CREATED =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("CREATED <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("CREATED >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("CREATED <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("CREATED <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("CREATED in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("CREATED not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("CREATED between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("CREATED not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("MODIFIED =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("MODIFIED <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("MODIFIED >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFIED >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("MODIFIED <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("MODIFIED <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("MODIFIED in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("MODIFIED not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("MODIFIED between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("MODIFIED not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("ISDEL is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("ISDEL is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(Short value) {
            addCriterion("ISDEL =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(Short value) {
            addCriterion("ISDEL <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(Short value) {
            addCriterion("ISDEL >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(Short value) {
            addCriterion("ISDEL >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(Short value) {
            addCriterion("ISDEL <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(Short value) {
            addCriterion("ISDEL <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<Short> values) {
            addCriterion("ISDEL in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<Short> values) {
            addCriterion("ISDEL not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(Short value1, Short value2) {
            addCriterion("ISDEL between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(Short value1, Short value2) {
            addCriterion("ISDEL not between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andPwMiscntIsNull() {
            addCriterion("PW_MISCNT is null");
            return (Criteria) this;
        }

        public Criteria andPwMiscntIsNotNull() {
            addCriterion("PW_MISCNT is not null");
            return (Criteria) this;
        }

        public Criteria andPwMiscntEqualTo(Short value) {
            addCriterion("PW_MISCNT =", value, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntNotEqualTo(Short value) {
            addCriterion("PW_MISCNT <>", value, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntGreaterThan(Short value) {
            addCriterion("PW_MISCNT >", value, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntGreaterThanOrEqualTo(Short value) {
            addCriterion("PW_MISCNT >=", value, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntLessThan(Short value) {
            addCriterion("PW_MISCNT <", value, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntLessThanOrEqualTo(Short value) {
            addCriterion("PW_MISCNT <=", value, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntIn(List<Short> values) {
            addCriterion("PW_MISCNT in", values, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntNotIn(List<Short> values) {
            addCriterion("PW_MISCNT not in", values, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntBetween(Short value1, Short value2) {
            addCriterion("PW_MISCNT between", value1, value2, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andPwMiscntNotBetween(Short value1, Short value2) {
            addCriterion("PW_MISCNT not between", value1, value2, "pwMiscnt");
            return (Criteria) this;
        }

        public Criteria andEx01IsNull() {
            addCriterion("EX01 is null");
            return (Criteria) this;
        }

        public Criteria andEx01IsNotNull() {
            addCriterion("EX01 is not null");
            return (Criteria) this;
        }

        public Criteria andEx01EqualTo(String value) {
            addCriterion("EX01 =", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01NotEqualTo(String value) {
            addCriterion("EX01 <>", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01GreaterThan(String value) {
            addCriterion("EX01 >", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01GreaterThanOrEqualTo(String value) {
            addCriterion("EX01 >=", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01LessThan(String value) {
            addCriterion("EX01 <", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01LessThanOrEqualTo(String value) {
            addCriterion("EX01 <=", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01Like(String value) {
            addCriterion("EX01 like", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01NotLike(String value) {
            addCriterion("EX01 not like", value, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01In(List<String> values) {
            addCriterion("EX01 in", values, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01NotIn(List<String> values) {
            addCriterion("EX01 not in", values, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01Between(String value1, String value2) {
            addCriterion("EX01 between", value1, value2, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx01NotBetween(String value1, String value2) {
            addCriterion("EX01 not between", value1, value2, "ex01");
            return (Criteria) this;
        }

        public Criteria andEx02IsNull() {
            addCriterion("EX02 is null");
            return (Criteria) this;
        }

        public Criteria andEx02IsNotNull() {
            addCriterion("EX02 is not null");
            return (Criteria) this;
        }

        public Criteria andEx02EqualTo(String value) {
            addCriterion("EX02 =", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02NotEqualTo(String value) {
            addCriterion("EX02 <>", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02GreaterThan(String value) {
            addCriterion("EX02 >", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02GreaterThanOrEqualTo(String value) {
            addCriterion("EX02 >=", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02LessThan(String value) {
            addCriterion("EX02 <", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02LessThanOrEqualTo(String value) {
            addCriterion("EX02 <=", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02Like(String value) {
            addCriterion("EX02 like", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02NotLike(String value) {
            addCriterion("EX02 not like", value, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02In(List<String> values) {
            addCriterion("EX02 in", values, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02NotIn(List<String> values) {
            addCriterion("EX02 not in", values, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02Between(String value1, String value2) {
            addCriterion("EX02 between", value1, value2, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx02NotBetween(String value1, String value2) {
            addCriterion("EX02 not between", value1, value2, "ex02");
            return (Criteria) this;
        }

        public Criteria andEx03IsNull() {
            addCriterion("EX03 is null");
            return (Criteria) this;
        }

        public Criteria andEx03IsNotNull() {
            addCriterion("EX03 is not null");
            return (Criteria) this;
        }

        public Criteria andEx03EqualTo(String value) {
            addCriterion("EX03 =", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03NotEqualTo(String value) {
            addCriterion("EX03 <>", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03GreaterThan(String value) {
            addCriterion("EX03 >", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03GreaterThanOrEqualTo(String value) {
            addCriterion("EX03 >=", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03LessThan(String value) {
            addCriterion("EX03 <", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03LessThanOrEqualTo(String value) {
            addCriterion("EX03 <=", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03Like(String value) {
            addCriterion("EX03 like", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03NotLike(String value) {
            addCriterion("EX03 not like", value, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03In(List<String> values) {
            addCriterion("EX03 in", values, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03NotIn(List<String> values) {
            addCriterion("EX03 not in", values, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03Between(String value1, String value2) {
            addCriterion("EX03 between", value1, value2, "ex03");
            return (Criteria) this;
        }

        public Criteria andEx03NotBetween(String value1, String value2) {
            addCriterion("EX03 not between", value1, value2, "ex03");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 05 23:25:09 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}