package jm.cms.model;

import java.util.Date;

public class CMS_MBRLOG {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBRLOG_ID
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrlogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBR_ID
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBRLOG_CONTENT
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrlogContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBRLOG_STATUS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private Short mbrlogStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.CREATED
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBR_NM
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBR_LOGIN
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBR_IP
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.ACT_MBR_LOGIN
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String actMbrLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBRLOG_PATH
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrlogPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRLOG.MBRLOG_EXT01
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    private String mbrlogExt01;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public CMS_MBRLOG(String mbrlogId, String mbrId, String mbrlogContent, Short mbrlogStatus, Date created, String mbrNm, String mbrLogin, String mbrIp, String actMbrLogin, String mbrlogPath, String mbrlogExt01) {
        this.mbrlogId = mbrlogId;
        this.mbrId = mbrId;
        this.mbrlogContent = mbrlogContent;
        this.mbrlogStatus = mbrlogStatus;
        this.created = created;
        this.mbrNm = mbrNm;
        this.mbrLogin = mbrLogin;
        this.mbrIp = mbrIp;
        this.actMbrLogin = actMbrLogin;
        this.mbrlogPath = mbrlogPath;
        this.mbrlogExt01 = mbrlogExt01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRLOG
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public CMS_MBRLOG() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBRLOG_ID
     *
     * @return the value of TB_CMSMBRLOG.MBRLOG_ID
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrlogId() {
        return mbrlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBRLOG_ID
     *
     * @param mbrlogId the value for TB_CMSMBRLOG.MBRLOG_ID
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrlogId(String mbrlogId) {
        this.mbrlogId = mbrlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBR_ID
     *
     * @return the value of TB_CMSMBRLOG.MBR_ID
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrId() {
        return mbrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBR_ID
     *
     * @param mbrId the value for TB_CMSMBRLOG.MBR_ID
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrId(String mbrId) {
        this.mbrId = mbrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBRLOG_CONTENT
     *
     * @return the value of TB_CMSMBRLOG.MBRLOG_CONTENT
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrlogContent() {
        return mbrlogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBRLOG_CONTENT
     *
     * @param mbrlogContent the value for TB_CMSMBRLOG.MBRLOG_CONTENT
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrlogContent(String mbrlogContent) {
        this.mbrlogContent = mbrlogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBRLOG_STATUS
     *
     * @return the value of TB_CMSMBRLOG.MBRLOG_STATUS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public Short getMbrlogStatus() {
        return mbrlogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBRLOG_STATUS
     *
     * @param mbrlogStatus the value for TB_CMSMBRLOG.MBRLOG_STATUS
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrlogStatus(Short mbrlogStatus) {
        this.mbrlogStatus = mbrlogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.CREATED
     *
     * @return the value of TB_CMSMBRLOG.CREATED
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.CREATED
     *
     * @param created the value for TB_CMSMBRLOG.CREATED
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBR_NM
     *
     * @return the value of TB_CMSMBRLOG.MBR_NM
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrNm() {
        return mbrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBR_NM
     *
     * @param mbrNm the value for TB_CMSMBRLOG.MBR_NM
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrNm(String mbrNm) {
        this.mbrNm = mbrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBR_LOGIN
     *
     * @return the value of TB_CMSMBRLOG.MBR_LOGIN
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrLogin() {
        return mbrLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBR_LOGIN
     *
     * @param mbrLogin the value for TB_CMSMBRLOG.MBR_LOGIN
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrLogin(String mbrLogin) {
        this.mbrLogin = mbrLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBR_IP
     *
     * @return the value of TB_CMSMBRLOG.MBR_IP
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrIp() {
        return mbrIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBR_IP
     *
     * @param mbrIp the value for TB_CMSMBRLOG.MBR_IP
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrIp(String mbrIp) {
        this.mbrIp = mbrIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.ACT_MBR_LOGIN
     *
     * @return the value of TB_CMSMBRLOG.ACT_MBR_LOGIN
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getActMbrLogin() {
        return actMbrLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.ACT_MBR_LOGIN
     *
     * @param actMbrLogin the value for TB_CMSMBRLOG.ACT_MBR_LOGIN
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setActMbrLogin(String actMbrLogin) {
        this.actMbrLogin = actMbrLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBRLOG_PATH
     *
     * @return the value of TB_CMSMBRLOG.MBRLOG_PATH
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrlogPath() {
        return mbrlogPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBRLOG_PATH
     *
     * @param mbrlogPath the value for TB_CMSMBRLOG.MBRLOG_PATH
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrlogPath(String mbrlogPath) {
        this.mbrlogPath = mbrlogPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRLOG.MBRLOG_EXT01
     *
     * @return the value of TB_CMSMBRLOG.MBRLOG_EXT01
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public String getMbrlogExt01() {
        return mbrlogExt01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRLOG.MBRLOG_EXT01
     *
     * @param mbrlogExt01 the value for TB_CMSMBRLOG.MBRLOG_EXT01
     *
     * @mbg.generated Fri Jun 05 23:25:09 KST 2020
     */
    public void setMbrlogExt01(String mbrlogExt01) {
        this.mbrlogExt01 = mbrlogExt01;
    }
}