package jm.cms.model;

import java.util.Date;

public class ComnCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.COMCD_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String comcdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.COMCD_CODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String comcdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.COMCD_NAME
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String comcdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.COMCD_PARENT_CODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String comcdParentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.COMCD_ORDER
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Integer comcdOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.COMCD_LEVEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Integer comcdLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.ISACTIVE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Short isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.CREATED_USER_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.MODIFIED_USER_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String modifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSCOMMONCODE.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Short isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public ComnCode(String comcdId, String comcdCode, String comcdName, String comcdParentCode, Integer comcdOrder, Integer comcdLevel, Short isactive, Date created, String createdUserId, Date modified, String modifiedUserId, Short isdel) {
        this.comcdId = comcdId;
        this.comcdCode = comcdCode;
        this.comcdName = comcdName;
        this.comcdParentCode = comcdParentCode;
        this.comcdOrder = comcdOrder;
        this.comcdLevel = comcdLevel;
        this.isactive = isactive;
        this.created = created;
        this.createdUserId = createdUserId;
        this.modified = modified;
        this.modifiedUserId = modifiedUserId;
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSCOMMONCODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public ComnCode() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.COMCD_ID
     *
     * @return the value of TB_CMSCOMMONCODE.COMCD_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getComcdId() {
        return comcdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.COMCD_ID
     *
     * @param comcdId the value for TB_CMSCOMMONCODE.COMCD_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setComcdId(String comcdId) {
        this.comcdId = comcdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.COMCD_CODE
     *
     * @return the value of TB_CMSCOMMONCODE.COMCD_CODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getComcdCode() {
        return comcdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.COMCD_CODE
     *
     * @param comcdCode the value for TB_CMSCOMMONCODE.COMCD_CODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setComcdCode(String comcdCode) {
        this.comcdCode = comcdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.COMCD_NAME
     *
     * @return the value of TB_CMSCOMMONCODE.COMCD_NAME
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getComcdName() {
        return comcdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.COMCD_NAME
     *
     * @param comcdName the value for TB_CMSCOMMONCODE.COMCD_NAME
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setComcdName(String comcdName) {
        this.comcdName = comcdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.COMCD_PARENT_CODE
     *
     * @return the value of TB_CMSCOMMONCODE.COMCD_PARENT_CODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getComcdParentCode() {
        return comcdParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.COMCD_PARENT_CODE
     *
     * @param comcdParentCode the value for TB_CMSCOMMONCODE.COMCD_PARENT_CODE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setComcdParentCode(String comcdParentCode) {
        this.comcdParentCode = comcdParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.COMCD_ORDER
     *
     * @return the value of TB_CMSCOMMONCODE.COMCD_ORDER
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Integer getComcdOrder() {
        return comcdOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.COMCD_ORDER
     *
     * @param comcdOrder the value for TB_CMSCOMMONCODE.COMCD_ORDER
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setComcdOrder(Integer comcdOrder) {
        this.comcdOrder = comcdOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.COMCD_LEVEL
     *
     * @return the value of TB_CMSCOMMONCODE.COMCD_LEVEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Integer getComcdLevel() {
        return comcdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.COMCD_LEVEL
     *
     * @param comcdLevel the value for TB_CMSCOMMONCODE.COMCD_LEVEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setComcdLevel(Integer comcdLevel) {
        this.comcdLevel = comcdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.ISACTIVE
     *
     * @return the value of TB_CMSCOMMONCODE.ISACTIVE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Short getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.ISACTIVE
     *
     * @param isactive the value for TB_CMSCOMMONCODE.ISACTIVE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setIsactive(Short isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.CREATED
     *
     * @return the value of TB_CMSCOMMONCODE.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.CREATED
     *
     * @param created the value for TB_CMSCOMMONCODE.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.CREATED_USER_ID
     *
     * @return the value of TB_CMSCOMMONCODE.CREATED_USER_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.CREATED_USER_ID
     *
     * @param createdUserId the value for TB_CMSCOMMONCODE.CREATED_USER_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.MODIFIED
     *
     * @return the value of TB_CMSCOMMONCODE.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.MODIFIED
     *
     * @param modified the value for TB_CMSCOMMONCODE.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.MODIFIED_USER_ID
     *
     * @return the value of TB_CMSCOMMONCODE.MODIFIED_USER_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.MODIFIED_USER_ID
     *
     * @param modifiedUserId the value for TB_CMSCOMMONCODE.MODIFIED_USER_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setModifiedUserId(String modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSCOMMONCODE.ISDEL
     *
     * @return the value of TB_CMSCOMMONCODE.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Short getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSCOMMONCODE.ISDEL
     *
     * @param isdel the value for TB_CMSCOMMONCODE.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setIsdel(Short isdel) {
        this.isdel = isdel;
    }
}