package jm.cms.model;

import java.util.Date;

public class IpConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSIPCONFIG.CMS_TYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String cmsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSIPCONFIG.PERMISSION_YN
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String permissionYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSIPCONFIG.MBR_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String mbrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSIPCONFIG.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSIPCONFIG.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public IpConfig(String cmsType, String permissionYn, String mbrId, Date created, Date modified) {
        this.cmsType = cmsType;
        this.permissionYn = permissionYn;
        this.mbrId = mbrId;
        this.created = created;
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSIPCONFIG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public IpConfig() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSIPCONFIG.CMS_TYPE
     *
     * @return the value of TB_CMSIPCONFIG.CMS_TYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getCmsType() {
        return cmsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSIPCONFIG.CMS_TYPE
     *
     * @param cmsType the value for TB_CMSIPCONFIG.CMS_TYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setCmsType(String cmsType) {
        this.cmsType = cmsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSIPCONFIG.PERMISSION_YN
     *
     * @return the value of TB_CMSIPCONFIG.PERMISSION_YN
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getPermissionYn() {
        return permissionYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSIPCONFIG.PERMISSION_YN
     *
     * @param permissionYn the value for TB_CMSIPCONFIG.PERMISSION_YN
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setPermissionYn(String permissionYn) {
        this.permissionYn = permissionYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSIPCONFIG.MBR_ID
     *
     * @return the value of TB_CMSIPCONFIG.MBR_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMbrId() {
        return mbrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSIPCONFIG.MBR_ID
     *
     * @param mbrId the value for TB_CMSIPCONFIG.MBR_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMbrId(String mbrId) {
        this.mbrId = mbrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSIPCONFIG.CREATED
     *
     * @return the value of TB_CMSIPCONFIG.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSIPCONFIG.CREATED
     *
     * @param created the value for TB_CMSIPCONFIG.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSIPCONFIG.MODIFIED
     *
     * @return the value of TB_CMSIPCONFIG.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSIPCONFIG.MODIFIED
     *
     * @param modified the value for TB_CMSIPCONFIG.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}