package jm.cms.model;

import java.util.Date;

public class MBR {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.MBR_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String mbrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.MBR_LOGIN
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String mbrLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.MBR_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String mbrNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.PASSWD
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.TYPE_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.POS_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String posNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.ORG_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String orgNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.EMAIL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.TEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Short isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.PW_MISCNT
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Short pwMiscnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.EX01
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String ex01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.EX02
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String ex02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBR.EX03
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String ex03;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public MBR(String mbrId, String mbrLogin, String mbrNm, String passwd, String typeId, String posNm, String orgNm, String email, String tel, Date created, Date modified, Short isdel, Short pwMiscnt, String ex01, String ex02, String ex03) {
        this.mbrId = mbrId;
        this.mbrLogin = mbrLogin;
        this.mbrNm = mbrNm;
        this.passwd = passwd;
        this.typeId = typeId;
        this.posNm = posNm;
        this.orgNm = orgNm;
        this.email = email;
        this.tel = tel;
        this.created = created;
        this.modified = modified;
        this.isdel = isdel;
        this.pwMiscnt = pwMiscnt;
        this.ex01 = ex01;
        this.ex02 = ex02;
        this.ex03 = ex03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBR
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public MBR() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.MBR_ID
     *
     * @return the value of TB_CMSMBR.MBR_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMbrId() {
        return mbrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.MBR_ID
     *
     * @param mbrId the value for TB_CMSMBR.MBR_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMbrId(String mbrId) {
        this.mbrId = mbrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.MBR_LOGIN
     *
     * @return the value of TB_CMSMBR.MBR_LOGIN
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMbrLogin() {
        return mbrLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.MBR_LOGIN
     *
     * @param mbrLogin the value for TB_CMSMBR.MBR_LOGIN
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMbrLogin(String mbrLogin) {
        this.mbrLogin = mbrLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.MBR_NM
     *
     * @return the value of TB_CMSMBR.MBR_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMbrNm() {
        return mbrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.MBR_NM
     *
     * @param mbrNm the value for TB_CMSMBR.MBR_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMbrNm(String mbrNm) {
        this.mbrNm = mbrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.PASSWD
     *
     * @return the value of TB_CMSMBR.PASSWD
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.PASSWD
     *
     * @param passwd the value for TB_CMSMBR.PASSWD
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.TYPE_ID
     *
     * @return the value of TB_CMSMBR.TYPE_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.TYPE_ID
     *
     * @param typeId the value for TB_CMSMBR.TYPE_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.POS_NM
     *
     * @return the value of TB_CMSMBR.POS_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getPosNm() {
        return posNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.POS_NM
     *
     * @param posNm the value for TB_CMSMBR.POS_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setPosNm(String posNm) {
        this.posNm = posNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.ORG_NM
     *
     * @return the value of TB_CMSMBR.ORG_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getOrgNm() {
        return orgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.ORG_NM
     *
     * @param orgNm the value for TB_CMSMBR.ORG_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setOrgNm(String orgNm) {
        this.orgNm = orgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.EMAIL
     *
     * @return the value of TB_CMSMBR.EMAIL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.EMAIL
     *
     * @param email the value for TB_CMSMBR.EMAIL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.TEL
     *
     * @return the value of TB_CMSMBR.TEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.TEL
     *
     * @param tel the value for TB_CMSMBR.TEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.CREATED
     *
     * @return the value of TB_CMSMBR.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.CREATED
     *
     * @param created the value for TB_CMSMBR.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.MODIFIED
     *
     * @return the value of TB_CMSMBR.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.MODIFIED
     *
     * @param modified the value for TB_CMSMBR.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.ISDEL
     *
     * @return the value of TB_CMSMBR.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Short getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.ISDEL
     *
     * @param isdel the value for TB_CMSMBR.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setIsdel(Short isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.PW_MISCNT
     *
     * @return the value of TB_CMSMBR.PW_MISCNT
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Short getPwMiscnt() {
        return pwMiscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.PW_MISCNT
     *
     * @param pwMiscnt the value for TB_CMSMBR.PW_MISCNT
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setPwMiscnt(Short pwMiscnt) {
        this.pwMiscnt = pwMiscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.EX01
     *
     * @return the value of TB_CMSMBR.EX01
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getEx01() {
        return ex01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.EX01
     *
     * @param ex01 the value for TB_CMSMBR.EX01
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setEx01(String ex01) {
        this.ex01 = ex01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.EX02
     *
     * @return the value of TB_CMSMBR.EX02
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getEx02() {
        return ex02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.EX02
     *
     * @param ex02 the value for TB_CMSMBR.EX02
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setEx02(String ex02) {
        this.ex02 = ex02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBR.EX03
     *
     * @return the value of TB_CMSMBR.EX03
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getEx03() {
        return ex03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBR.EX03
     *
     * @param ex03 the value for TB_CMSMBR.EX03
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setEx03(String ex03) {
        this.ex03 = ex03;
    }
}