package jm.cms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MbrSessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public MbrSessExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMbrIdIsNull() {
            addCriterion("MBR_ID is null");
            return (Criteria) this;
        }

        public Criteria andMbrIdIsNotNull() {
            addCriterion("MBR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMbrIdEqualTo(String value) {
            addCriterion("MBR_ID =", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotEqualTo(String value) {
            addCriterion("MBR_ID <>", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThan(String value) {
            addCriterion("MBR_ID >", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_ID >=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThan(String value) {
            addCriterion("MBR_ID <", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThanOrEqualTo(String value) {
            addCriterion("MBR_ID <=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLike(String value) {
            addCriterion("MBR_ID like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotLike(String value) {
            addCriterion("MBR_ID not like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdIn(List<String> values) {
            addCriterion("MBR_ID in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotIn(List<String> values) {
            addCriterion("MBR_ID not in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdBetween(String value1, String value2) {
            addCriterion("MBR_ID between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotBetween(String value1, String value2) {
            addCriterion("MBR_ID not between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrSessIsNull() {
            addCriterion("MBR_SESS is null");
            return (Criteria) this;
        }

        public Criteria andMbrSessIsNotNull() {
            addCriterion("MBR_SESS is not null");
            return (Criteria) this;
        }

        public Criteria andMbrSessEqualTo(String value) {
            addCriterion("MBR_SESS =", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessNotEqualTo(String value) {
            addCriterion("MBR_SESS <>", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessGreaterThan(String value) {
            addCriterion("MBR_SESS >", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessGreaterThanOrEqualTo(String value) {
            addCriterion("MBR_SESS >=", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessLessThan(String value) {
            addCriterion("MBR_SESS <", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessLessThanOrEqualTo(String value) {
            addCriterion("MBR_SESS <=", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessLike(String value) {
            addCriterion("MBR_SESS like", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessNotLike(String value) {
            addCriterion("MBR_SESS not like", value, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessIn(List<String> values) {
            addCriterion("MBR_SESS in", values, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessNotIn(List<String> values) {
            addCriterion("MBR_SESS not in", values, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessBetween(String value1, String value2) {
            addCriterion("MBR_SESS between", value1, value2, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andMbrSessNotBetween(String value1, String value2) {
            addCriterion("MBR_SESS not between", value1, value2, "mbrSess");
            return (Criteria) this;
        }

        public Criteria andSessLockIsNull() {
            addCriterion("SESS_LOCK is null");
            return (Criteria) this;
        }

        public Criteria andSessLockIsNotNull() {
            addCriterion("SESS_LOCK is not null");
            return (Criteria) this;
        }

        public Criteria andSessLockEqualTo(Long value) {
            addCriterion("SESS_LOCK =", value, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockNotEqualTo(Long value) {
            addCriterion("SESS_LOCK <>", value, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockGreaterThan(Long value) {
            addCriterion("SESS_LOCK >", value, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockGreaterThanOrEqualTo(Long value) {
            addCriterion("SESS_LOCK >=", value, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockLessThan(Long value) {
            addCriterion("SESS_LOCK <", value, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockLessThanOrEqualTo(Long value) {
            addCriterion("SESS_LOCK <=", value, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockIn(List<Long> values) {
            addCriterion("SESS_LOCK in", values, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockNotIn(List<Long> values) {
            addCriterion("SESS_LOCK not in", values, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockBetween(Long value1, Long value2) {
            addCriterion("SESS_LOCK between", value1, value2, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessLockNotBetween(Long value1, Long value2) {
            addCriterion("SESS_LOCK not between", value1, value2, "sessLock");
            return (Criteria) this;
        }

        public Criteria andSessDateIsNull() {
            addCriterion("SESS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSessDateIsNotNull() {
            addCriterion("SESS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSessDateEqualTo(Date value) {
            addCriterion("SESS_DATE =", value, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateNotEqualTo(Date value) {
            addCriterion("SESS_DATE <>", value, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateGreaterThan(Date value) {
            addCriterion("SESS_DATE >", value, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SESS_DATE >=", value, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateLessThan(Date value) {
            addCriterion("SESS_DATE <", value, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateLessThanOrEqualTo(Date value) {
            addCriterion("SESS_DATE <=", value, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateIn(List<Date> values) {
            addCriterion("SESS_DATE in", values, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateNotIn(List<Date> values) {
            addCriterion("SESS_DATE not in", values, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateBetween(Date value1, Date value2) {
            addCriterion("SESS_DATE between", value1, value2, "sessDate");
            return (Criteria) this;
        }

        public Criteria andSessDateNotBetween(Date value1, Date value2) {
            addCriterion("SESS_DATE not between", value1, value2, "sessDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 06 11:44:28 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSMBRSESS
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}