package jm.cms.model;

import java.util.Date;

public class MbrType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRTYPE.TYPE_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRTYPE.TYPE_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String typeNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRTYPE.TYPE_LV
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String typeLv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRTYPE.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRTYPE.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSMBRTYPE.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Short isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public MbrType(String typeId, String typeNm, String typeLv, Date created, Date modified, Short isdel) {
        this.typeId = typeId;
        this.typeNm = typeNm;
        this.typeLv = typeLv;
        this.created = created;
        this.modified = modified;
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSMBRTYPE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public MbrType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRTYPE.TYPE_ID
     *
     * @return the value of TB_CMSMBRTYPE.TYPE_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRTYPE.TYPE_ID
     *
     * @param typeId the value for TB_CMSMBRTYPE.TYPE_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRTYPE.TYPE_NM
     *
     * @return the value of TB_CMSMBRTYPE.TYPE_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getTypeNm() {
        return typeNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRTYPE.TYPE_NM
     *
     * @param typeNm the value for TB_CMSMBRTYPE.TYPE_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setTypeNm(String typeNm) {
        this.typeNm = typeNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRTYPE.TYPE_LV
     *
     * @return the value of TB_CMSMBRTYPE.TYPE_LV
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getTypeLv() {
        return typeLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRTYPE.TYPE_LV
     *
     * @param typeLv the value for TB_CMSMBRTYPE.TYPE_LV
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setTypeLv(String typeLv) {
        this.typeLv = typeLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRTYPE.CREATED
     *
     * @return the value of TB_CMSMBRTYPE.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRTYPE.CREATED
     *
     * @param created the value for TB_CMSMBRTYPE.CREATED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRTYPE.MODIFIED
     *
     * @return the value of TB_CMSMBRTYPE.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRTYPE.MODIFIED
     *
     * @param modified the value for TB_CMSMBRTYPE.MODIFIED
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSMBRTYPE.ISDEL
     *
     * @return the value of TB_CMSMBRTYPE.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Short getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSMBRTYPE.ISDEL
     *
     * @param isdel the value for TB_CMSMBRTYPE.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setIsdel(Short isdel) {
        this.isdel = isdel;
    }
}