package jm.cms.model;

public class MenuInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.UPPER_MENU_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String upperMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_DEPTH
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Integer menuDepth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_ODR
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private Integer menuOdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_ICON
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String menuIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String menuNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_LINK
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String menuLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.ISACTIVE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.CANNOTDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String cannotdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_DESC
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String menuDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CMSADMENUINFO.MENU_NM_ICON
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    private String menuNmIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUINFO
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public MenuInfo(String menuId, String upperMenuId, Integer menuDepth, Integer menuOdr, String menuIcon, String menuNm, String menuLink, String isactive, String isdel, String cannotdel, String menuDesc, String menuNmIcon) {
        this.menuId = menuId;
        this.upperMenuId = upperMenuId;
        this.menuDepth = menuDepth;
        this.menuOdr = menuOdr;
        this.menuIcon = menuIcon;
        this.menuNm = menuNm;
        this.menuLink = menuLink;
        this.isactive = isactive;
        this.isdel = isdel;
        this.cannotdel = cannotdel;
        this.menuDesc = menuDesc;
        this.menuNmIcon = menuNmIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSADMENUINFO
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public MenuInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_ID
     *
     * @return the value of TB_CMSADMENUINFO.MENU_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_ID
     *
     * @param menuId the value for TB_CMSADMENUINFO.MENU_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.UPPER_MENU_ID
     *
     * @return the value of TB_CMSADMENUINFO.UPPER_MENU_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getUpperMenuId() {
        return upperMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.UPPER_MENU_ID
     *
     * @param upperMenuId the value for TB_CMSADMENUINFO.UPPER_MENU_ID
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setUpperMenuId(String upperMenuId) {
        this.upperMenuId = upperMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_DEPTH
     *
     * @return the value of TB_CMSADMENUINFO.MENU_DEPTH
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Integer getMenuDepth() {
        return menuDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_DEPTH
     *
     * @param menuDepth the value for TB_CMSADMENUINFO.MENU_DEPTH
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuDepth(Integer menuDepth) {
        this.menuDepth = menuDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_ODR
     *
     * @return the value of TB_CMSADMENUINFO.MENU_ODR
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Integer getMenuOdr() {
        return menuOdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_ODR
     *
     * @param menuOdr the value for TB_CMSADMENUINFO.MENU_ODR
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuOdr(Integer menuOdr) {
        this.menuOdr = menuOdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_ICON
     *
     * @return the value of TB_CMSADMENUINFO.MENU_ICON
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_ICON
     *
     * @param menuIcon the value for TB_CMSADMENUINFO.MENU_ICON
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_NM
     *
     * @return the value of TB_CMSADMENUINFO.MENU_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMenuNm() {
        return menuNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_NM
     *
     * @param menuNm the value for TB_CMSADMENUINFO.MENU_NM
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuNm(String menuNm) {
        this.menuNm = menuNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_LINK
     *
     * @return the value of TB_CMSADMENUINFO.MENU_LINK
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMenuLink() {
        return menuLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_LINK
     *
     * @param menuLink the value for TB_CMSADMENUINFO.MENU_LINK
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.ISACTIVE
     *
     * @return the value of TB_CMSADMENUINFO.ISACTIVE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.ISACTIVE
     *
     * @param isactive the value for TB_CMSADMENUINFO.ISACTIVE
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.ISDEL
     *
     * @return the value of TB_CMSADMENUINFO.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.ISDEL
     *
     * @param isdel the value for TB_CMSADMENUINFO.ISDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.CANNOTDEL
     *
     * @return the value of TB_CMSADMENUINFO.CANNOTDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getCannotdel() {
        return cannotdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.CANNOTDEL
     *
     * @param cannotdel the value for TB_CMSADMENUINFO.CANNOTDEL
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setCannotdel(String cannotdel) {
        this.cannotdel = cannotdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_DESC
     *
     * @return the value of TB_CMSADMENUINFO.MENU_DESC
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_DESC
     *
     * @param menuDesc the value for TB_CMSADMENUINFO.MENU_DESC
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CMSADMENUINFO.MENU_NM_ICON
     *
     * @return the value of TB_CMSADMENUINFO.MENU_NM_ICON
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getMenuNmIcon() {
        return menuNmIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CMSADMENUINFO.MENU_NM_ICON
     *
     * @param menuNmIcon the value for TB_CMSADMENUINFO.MENU_NM_ICON
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setMenuNmIcon(String menuNmIcon) {
        this.menuNmIcon = menuNmIcon;
    }
}