package jm.cms.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VisitLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public VisitLogExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqNoIsNull() {
            addCriterion("SEQ_NO is null");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNotNull() {
            addCriterion("SEQ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNoEqualTo(BigDecimal value) {
            addCriterion("SEQ_NO =", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotEqualTo(BigDecimal value) {
            addCriterion("SEQ_NO <>", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThan(BigDecimal value) {
            addCriterion("SEQ_NO >", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SEQ_NO >=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThan(BigDecimal value) {
            addCriterion("SEQ_NO <", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SEQ_NO <=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoIn(List<BigDecimal> values) {
            addCriterion("SEQ_NO in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotIn(List<BigDecimal> values) {
            addCriterion("SEQ_NO not in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEQ_NO between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEQ_NO not between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNull() {
            addCriterion("SITE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNotNull() {
            addCriterion("SITE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIdEqualTo(String value) {
            addCriterion("SITE_ID =", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotEqualTo(String value) {
            addCriterion("SITE_ID <>", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThan(String value) {
            addCriterion("SITE_ID >", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThanOrEqualTo(String value) {
            addCriterion("SITE_ID >=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThan(String value) {
            addCriterion("SITE_ID <", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThanOrEqualTo(String value) {
            addCriterion("SITE_ID <=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLike(String value) {
            addCriterion("SITE_ID like", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotLike(String value) {
            addCriterion("SITE_ID not like", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIn(List<String> values) {
            addCriterion("SITE_ID in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotIn(List<String> values) {
            addCriterion("SITE_ID not in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdBetween(String value1, String value2) {
            addCriterion("SITE_ID between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotBetween(String value1, String value2) {
            addCriterion("SITE_ID not between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andPageIdIsNull() {
            addCriterion("PAGE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPageIdIsNotNull() {
            addCriterion("PAGE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPageIdEqualTo(String value) {
            addCriterion("PAGE_ID =", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdNotEqualTo(String value) {
            addCriterion("PAGE_ID <>", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdGreaterThan(String value) {
            addCriterion("PAGE_ID >", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdGreaterThanOrEqualTo(String value) {
            addCriterion("PAGE_ID >=", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdLessThan(String value) {
            addCriterion("PAGE_ID <", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdLessThanOrEqualTo(String value) {
            addCriterion("PAGE_ID <=", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdLike(String value) {
            addCriterion("PAGE_ID like", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdNotLike(String value) {
            addCriterion("PAGE_ID not like", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdIn(List<String> values) {
            addCriterion("PAGE_ID in", values, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdNotIn(List<String> values) {
            addCriterion("PAGE_ID not in", values, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdBetween(String value1, String value2) {
            addCriterion("PAGE_ID between", value1, value2, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdNotBetween(String value1, String value2) {
            addCriterion("PAGE_ID not between", value1, value2, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageNmIsNull() {
            addCriterion("PAGE_NM is null");
            return (Criteria) this;
        }

        public Criteria andPageNmIsNotNull() {
            addCriterion("PAGE_NM is not null");
            return (Criteria) this;
        }

        public Criteria andPageNmEqualTo(String value) {
            addCriterion("PAGE_NM =", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmNotEqualTo(String value) {
            addCriterion("PAGE_NM <>", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmGreaterThan(String value) {
            addCriterion("PAGE_NM >", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmGreaterThanOrEqualTo(String value) {
            addCriterion("PAGE_NM >=", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmLessThan(String value) {
            addCriterion("PAGE_NM <", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmLessThanOrEqualTo(String value) {
            addCriterion("PAGE_NM <=", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmLike(String value) {
            addCriterion("PAGE_NM like", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmNotLike(String value) {
            addCriterion("PAGE_NM not like", value, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmIn(List<String> values) {
            addCriterion("PAGE_NM in", values, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmNotIn(List<String> values) {
            addCriterion("PAGE_NM not in", values, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmBetween(String value1, String value2) {
            addCriterion("PAGE_NM between", value1, value2, "pageNm");
            return (Criteria) this;
        }

        public Criteria andPageNmNotBetween(String value1, String value2) {
            addCriterion("PAGE_NM not between", value1, value2, "pageNm");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeIsNull() {
            addCriterion("WHEN_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeIsNotNull() {
            addCriterion("WHEN_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeEqualTo(Date value) {
            addCriterion("WHEN_DATETIME =", value, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeNotEqualTo(Date value) {
            addCriterion("WHEN_DATETIME <>", value, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeGreaterThan(Date value) {
            addCriterion("WHEN_DATETIME >", value, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("WHEN_DATETIME >=", value, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeLessThan(Date value) {
            addCriterion("WHEN_DATETIME <", value, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("WHEN_DATETIME <=", value, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeIn(List<Date> values) {
            addCriterion("WHEN_DATETIME in", values, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeNotIn(List<Date> values) {
            addCriterion("WHEN_DATETIME not in", values, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeBetween(Date value1, Date value2) {
            addCriterion("WHEN_DATETIME between", value1, value2, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("WHEN_DATETIME not between", value1, value2, "whenDatetime");
            return (Criteria) this;
        }

        public Criteria andWhenDateIsNull() {
            addCriterion("WHEN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andWhenDateIsNotNull() {
            addCriterion("WHEN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andWhenDateEqualTo(String value) {
            addCriterion("WHEN_DATE =", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateNotEqualTo(String value) {
            addCriterion("WHEN_DATE <>", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateGreaterThan(String value) {
            addCriterion("WHEN_DATE >", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateGreaterThanOrEqualTo(String value) {
            addCriterion("WHEN_DATE >=", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateLessThan(String value) {
            addCriterion("WHEN_DATE <", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateLessThanOrEqualTo(String value) {
            addCriterion("WHEN_DATE <=", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateLike(String value) {
            addCriterion("WHEN_DATE like", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateNotLike(String value) {
            addCriterion("WHEN_DATE not like", value, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateIn(List<String> values) {
            addCriterion("WHEN_DATE in", values, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateNotIn(List<String> values) {
            addCriterion("WHEN_DATE not in", values, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateBetween(String value1, String value2) {
            addCriterion("WHEN_DATE between", value1, value2, "whenDate");
            return (Criteria) this;
        }

        public Criteria andWhenDateNotBetween(String value1, String value2) {
            addCriterion("WHEN_DATE not between", value1, value2, "whenDate");
            return (Criteria) this;
        }

        public Criteria andIpaddrIsNull() {
            addCriterion("IPADDR is null");
            return (Criteria) this;
        }

        public Criteria andIpaddrIsNotNull() {
            addCriterion("IPADDR is not null");
            return (Criteria) this;
        }

        public Criteria andIpaddrEqualTo(String value) {
            addCriterion("IPADDR =", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotEqualTo(String value) {
            addCriterion("IPADDR <>", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrGreaterThan(String value) {
            addCriterion("IPADDR >", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrGreaterThanOrEqualTo(String value) {
            addCriterion("IPADDR >=", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrLessThan(String value) {
            addCriterion("IPADDR <", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrLessThanOrEqualTo(String value) {
            addCriterion("IPADDR <=", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrLike(String value) {
            addCriterion("IPADDR like", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotLike(String value) {
            addCriterion("IPADDR not like", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrIn(List<String> values) {
            addCriterion("IPADDR in", values, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotIn(List<String> values) {
            addCriterion("IPADDR not in", values, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrBetween(String value1, String value2) {
            addCriterion("IPADDR between", value1, value2, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotBetween(String value1, String value2) {
            addCriterion("IPADDR not between", value1, value2, "ipaddr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 06 11:44:28 KST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CMSVISITLOG
     *
     * @mbg.generated Sat Jun 06 11:44:28 KST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}